console.log("01 Seleccione las cacerolas a utilizar");
console.log("02 Engrasar y precalentar");
console.log("03 Prepare sus ingredientes");
console.log("04 Batir la mezcla seca");
console.log("05 Crema tu mantequilla y azúcar");
console.log("06 Agregue los huevos");
console.log("07 Es hora de combinar");
console.log("08 Vierta su masa en su sartén");
console.log("09 Hornee y enfríe sus pasteles");
console.log("10 Decore sus pasteles a gusto");
